{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      "[2024-02-02 16:40:24,100] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:24] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:24,478] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:24] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:24,683] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:24] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:24,859] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:24] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,031] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,197] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,375] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,546] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,717] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:25,870] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:25] \"GET / HTTP/1.1\" 500 -\n",
      "[2024-02-02 16:40:26,014] ERROR in app: Exception on / [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1463, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 872, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 870, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 855, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "  File \"/tmp/ipykernel_18302/2071226510.py\", line 19, in view_form\n",
      "    return render_template('login.html')\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 150, in render_template\n",
      "    return _render(app, template, context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/templating.py\", line 131, in _render\n",
      "    rv = template.render(context)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 1301, in render\n",
      "    self.environment.handle_exception()\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/jinja2/environment.py\", line 936, in handle_exception\n",
      "    raise rewrite_traceback_stack(source=source)\n",
      "  File \"/home/prabhav/Desktop/iss/flask/templates/login.html\", line 25, in top-level template code\n",
      "    <form method=\"GET\" action=\"{{ url_for('handle_get') }}\">\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1074, in url_for\n",
      "    return self.handle_url_build_error(error, endpoint, values)\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/flask/app.py\", line 1063, in url_for\n",
      "    rv = url_adapter.build(  # type: ignore[union-attr]\n",
      "  File \"/home/prabhav/.local/lib/python3.10/site-packages/werkzeug/routing/map.py\", line 919, in build\n",
      "    raise BuildError(endpoint, values, method, self)\n",
      "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'handle_get'. Did you mean 'view_form' instead?\n",
      "127.0.0.1 - - [02/Feb/2024 16:40:26] \"GET / HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "# app.py\n",
    "\n",
    "from flask import Flask, render_template, request, redirect, session\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Set a secret key for encrypting session data\n",
    "app.secret_key = 'my_secret_key'\n",
    "\n",
    "# dictionary to store user and password\n",
    "users = {\n",
    "\t'kunal': '1234',\n",
    "\t'user2': 'password2'\n",
    "}\n",
    "\n",
    "# To render a login form \n",
    "@app.route('/')\n",
    "def view_form():\n",
    "\treturn render_template('login.html')\n",
    "\n",
    "# For handling get request form we can get\n",
    "# the form inputs value by using args attribute.\n",
    "# this values after submitting you will see in the urls.\n",
    "# e.g http://127.0.0.1:5000/handle_get?username=kunal&password=1234\n",
    "# this exploits our credentials so that's \n",
    "# why developers prefer POST request.\n",
    "# @app.route('/handle_get', methods=['GET'])\n",
    "# def handle_get():\n",
    "# \tif request.method == 'GET':\n",
    "# \t\tusername = request.args['username']\n",
    "# \t\tpassword = request.args['password']\n",
    "# \t\tprint(username, password)\n",
    "# \t\tif username in users and users[username] == password:\n",
    "# \t\t\treturn '<h1>Welcome!!!</h1>'\n",
    "# \t\telse:\n",
    "# \t\t\treturn '<h1>invalid credentials!</h1>'\n",
    "# \telse:\n",
    "# \t\treturn render_template('login.html')\n",
    "\n",
    "# For handling post request form we can get the form\n",
    "# inputs value by using POST attribute.\n",
    "# this values after submitting you will never see in the urls.\n",
    "# @app.route('/handle_post', methods=['POST'])\n",
    "# def handle_post():\n",
    "# \tif request.method == 'POST':\n",
    "# \t\tusername = request.form['username']\n",
    "# \t\tpassword = request.form['password']\n",
    "# \t\tprint(username, password)\n",
    "# \t\tif username in users and users[username] == password:\n",
    "# \t\t\treturn '<h1>Welcome!!!</h1>'\n",
    "# \t\telse:\n",
    "# \t\t\treturn '<h1>invalid credentials!</h1>'\n",
    "# \telse:\n",
    "# \t\treturn render_template('login.html')\n",
    "\n",
    "if __name__ == '__main__':\n",
    "\tapp.run()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
